# Generated by Django 4.2.1 on 2023-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(verbose_name='Дата представления'),
        ),
    ]
