# Generated by Django 4.2.1 on 2023-05-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatreapp', '0002_alter_performance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=80, unique=True)),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theatreapp.hall'),
        ),
    ]
