# Generated by Django 4.2.1 on 2023-05-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatreapp', '0003_hall_performance_seats_performance_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theatreapp.performance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seat', 'row', 'seance')},
            },
        ),
    ]
