# Generated by Django 4.2.1 on 2023-05-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatreapp', '0004_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
    ]
