# Generated by Django 4.2.1 on 2023-06-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatreapp', '0007_remove_ticket_user_ticket_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='seats',
        ),
    ]
